ALTER TABLE task
    ALTER COLUMN time_total TYPE BIGINT USING EXTRACT(EPOCH FROM time_total);

ALTER TABLE task
    ALTER COLUMN rest_total TYPE BIGINT USING EXTRACT(EPOCH FROM rest_total);

ALTER TABLE demand
    ALTER COLUMN total_time TYPE BIGINT USING EXTRACT(EPOCH FROM total_time);